# Generated by Django 5.1.4 on 2025-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='type_utils',
            field=models.CharField(default='unassigned', max_length=255, verbose_name='Type of user'),
        ),
    ]
