# Generated by Django 5.1.4 on 2025-02-10 14:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_auto_add_date_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='enterprise_email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='enterprise_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 14, 5, 26, 795877, tzinfo=datetime.timezone.utc)),
        ),
    ]
