# Generated by Django 5.1.4 on 2025-02-11 13:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_job_date_posted_job_enterprise_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.JSONField(blank=True, default='Unkown'),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.JSONField(blank=True, default='Unkown'),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 13, 41, 29, 322984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='backapp.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='backapp.cv')),
            ],
        ),
    ]
