# Generated by Django 5.1.4 on 2025-02-11 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_cv_address_cv_education_cv_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='cv',
            name='description',
            field=models.TextField(default='Nothing to say'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 14, 23, 49, 68505, tzinfo=datetime.timezone.utc)),
        ),
    ]
