# Generated by Django 5.1.6 on 2025-02-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_add_extracted_text_to_cv'),
        ('backapp', '0005_remove_cv_address_remove_cv_education_and_more'),
    ]

    operations = [
    ]
