# Generated by Django 5.1.6 on 2025-02-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_add_user_to_job'),
        ('backapp', '0006_merge_20250213_0903'),
    ]

    operations = [
    ]
