# Generated by Django 5.1.6 on 2025-02-13 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0007_merge_0003_add_user_to_job_0006_merge_20250213_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 10, 2, 12, 740075, tzinfo=datetime.timezone.utc)),
        ),
    ]
