# Generated by Django 5.1.6 on 2025-02-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_create_entreprise_table'),
        ('backapp', '0008_alter_job_date_expire'),
    ]

    operations = [
    ]
