# Generated by Django 5.1.6 on 2025-02-13 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0009_merge_20250213_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 10, 21, 47, 531120, tzinfo=datetime.timezone.utc)),
        ),
    ]
