# Generated by Django 5.1.6 on 2025-02-13 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0011_alter_job_date_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 21, 10, 46, 759397, tzinfo=datetime.timezone.utc)),
        ),
    ]
